import uuid
from fpdf import FPDF
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from fastapi.responses import Response
from app.api.dependencies import get_session
from app.core.exceptions import NotFoundError
from app.schemas.job import JobCreate, JobRead
from app.services.job_service import JobService

router = APIRouter(prefix="/api/jobs", tags=["jobs"])


def _to_read(job) -> JobRead:
    return JobRead(
        id=job.id,
        title=job.title,
        raw_description=job.raw_description,
        required_skills=(job.required_skills or "").split("|") if job.required_skills else [],
        preferred_skills=(job.preferred_skills or "").split("|") if job.preferred_skills else [],
        responsibilities=(job.responsibilities or "").split("|") if job.responsibilities else [],
        qualifications=(job.qualifications or "").split("|") if job.qualifications else [],
        minimum_experience_years=job.minimum_experience_years,
        education_requirement=job.education_requirement,
        created_at=job.created_at,
        updated_at=job.updated_at,
    )


@router.post("", response_model=JobRead, status_code=201)
def create_job(payload: JobCreate, db: Session = Depends(get_session)) -> JobRead:
    service = JobService(db)
    job = service.create_job(payload)
    return _to_read(job)


@router.get("", response_model=list[JobRead])
def list_jobs(limit: int = 50, offset: int = 0, db: Session = Depends(get_session)) -> list[JobRead]:
    service = JobService(db)
    return [_to_read(j) for j in service.list_all(limit, offset)]


@router.get("/{job_id}", response_model=JobRead)
def get_job(job_id: uuid.UUID, db: Session = Depends(get_session)) -> JobRead:
    service = JobService(db)
    job = service.get(job_id)
    if not job:
        raise NotFoundError(f"Job {job_id} was not found")
    return _to_read(job)


from app.schemas.screening import RankingEntry, RankingResponse
from app.services.screening.screening_service import ScreeningService


@router.get("/{job_id}/rankings", response_model=RankingResponse)
def get_job_rankings(job_id: uuid.UUID, db: Session = Depends(get_session)) -> RankingResponse:
    job_service = JobService(db)
    job = job_service.get(job_id)
    if not job:
        raise NotFoundError(f"Job {job_id} was not found")

    screening_service = ScreeningService(db)
    scores = screening_service.rankings_for_job(job_id)

    entries = []
    for rank, score in enumerate(scores, start=1):
        matched = [ss.skill.name for ss in score.score_skills if ss.match_type == "matched"]
        missing = [ss.skill.name for ss in score.score_skills if ss.match_type == "missing"]
        entries.append(
            RankingEntry(
                rank=rank,
                candidate_id=score.candidate_id,
                candidate_name=score.candidate.name,
                overall_score=score.overall_score,
                skills_score=score.skills_score,
                experience_score=score.experience_score,
                matched_skills=matched,
                missing_skills=missing,
            )
        )

    return RankingResponse(job_id=job.id, job_title=job.title, rankings=entries)


@router.get("/{job_id}/report/pdf")
def get_job_shortlist_pdf(job_id: uuid.UUID, db: Session = Depends(get_session)):
    job_service = JobService(db)
    job = job_service.get(job_id)
    if not job:
        raise NotFoundError(f"Job {job_id} was not found")

    screening_service = ScreeningService(db)
    scores = screening_service.rankings_for_job(job_id)

    # 1. Initialize PDF
    pdf = FPDF()
    pdf.add_page()
    
    # 2. Add Headers
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, f"Final Shortlist Report: {job.title}", new_x="LMARGIN", new_y="NEXT", align="C")
    
    pdf.set_font("helvetica", "I", 10)
    pdf.cell(0, 10, "Generated by AI Resume Screener", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # 3. Add Table Headers
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(15, 10, "Rank", border=1, align="C")
    pdf.cell(65, 10, "Candidate Name", border=1, align="L")
    pdf.cell(25, 10, "Score", border=1, align="C")
    pdf.cell(85, 10, "Top Matched Skills", border=1, align="L")
    pdf.ln()

    # 4. Add Table Data
    pdf.set_font("helvetica", "", 10)
    for rank, score in enumerate(scores, start=1):
        matched = [ss.skill.name for ss in score.score_skills if ss.match_type == "matched"]
        skills_str = ", ".join(matched[:5]) # Show top 5 skills
        
        # Truncate skills string if it's too long for the cell
        if len(skills_str) > 45:
            skills_str = skills_str[:42] + "..."
            
        pdf.cell(15, 10, str(rank), border=1, align="C")
        pdf.cell(65, 10, score.candidate.name, border=1, align="L")
        pdf.cell(25, 10, f"{score.overall_score}/100", border=1, align="C")
        pdf.cell(85, 10, skills_str, border=1, align="L")
        pdf.ln()

    # 5. Output PDF as bytes
    pdf_bytes = pdf.output()

    # 6. Return as downloadable file
    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=shortlist_{job.id}.pdf"}
    )