"""initial schema

Revision ID: 590c3778d160
Revises: 
Create Date: 2026-08-06 11:49:12.526699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models.base


# revision identifiers, used by Alembic.
revision: str = '590c3778d160'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=True),
    sa.Column('education_summary', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.create_index(op.f('ix_candidates_total_experience_years'), 'candidates', ['total_experience_years'], unique=False)
    op.create_table('jobs',
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('preferred_skills', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('minimum_experience_years', sa.Float(), nullable=True),
    sa.Column('education_requirement', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('skills',
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_skill_normalized_name')
    )
    op.create_index(op.f('ix_skills_normalized_name'), 'skills', ['normalized_name'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('candidate_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('skill_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('proficiency', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'skill_id', name='uq_candidate_skill')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_id'), 'candidate_skills', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_skills_skill_id'), 'candidate_skills', ['skill_id'], unique=False)
    op.create_table('resume_files',
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('candidate_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_files_candidate_id'), 'resume_files', ['candidate_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('candidate_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('job_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('skills_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('education_score', sa.Float(), nullable=False),
    sa.Column('other_score', sa.Float(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_candidate_id'), 'scores', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_scores_job_id'), 'scores', ['job_id'], unique=False)
    op.create_index(op.f('ix_scores_overall_score'), 'scores', ['overall_score'], unique=False)
    op.create_table('score_skills',
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('score_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('skill_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_skills_score_id'), 'score_skills', ['score_id'], unique=False)
    op.create_index(op.f('ix_score_skills_skill_id'), 'score_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_skills_skill_id'), table_name='score_skills')
    op.drop_index(op.f('ix_score_skills_score_id'), table_name='score_skills')
    op.drop_table('score_skills')
    op.drop_index(op.f('ix_scores_overall_score'), table_name='scores')
    op.drop_index(op.f('ix_scores_job_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_candidate_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_resume_files_candidate_id'), table_name='resume_files')
    op.drop_table('resume_files')
    op.drop_index(op.f('ix_candidate_skills_skill_id'), table_name='candidate_skills')
    op.drop_index(op.f('ix_candidate_skills_candidate_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index(op.f('ix_skills_normalized_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_candidates_total_experience_years'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
